trigger:
  branches:
    include:
      - main  # Replace with the branch you want to trigger the pipeline

stages:
  - stage: InvokePegaAPI
    displayName: Invoke Pega REST API
    jobs:
      - job: InvokePegaAPIJob
        displayName: Invoke Pega API
        steps:
          - task: AzurePowerShell@5
            displayName: 'Invoke Pega API'
            inputs:
              azureSubscription: '10032001F5EBE945'
              ScriptType: 'InlineScript'
              Inline: |
                $uri = https://jsonplaceholder.typicode.com/posts/1  # Example API URL from GitHub
                $headers = @{
                  "Content-Type" = "application/json"
                }
                $response = Invoke-RestMethod -Uri $uri -Headers $headers -Method Get
                Write-Output $response
